### ISSUE TITLE
Guidelines in practice section

### ISSUE THREAD

**Issue by joschirr** [openaire/guidelines#20]
we have this section "Guidelines in practice" on the start page of the guidelines.
It was never used so far.
I'd like to hide it until we want publish practical examples or solutions.

**Comment by lnielsen** [comment]
I've removed the text now, and I think we can close the issue?

**Comment by ACz-UniBi** [comment]
No comments in the last five years. I close this ticket. Re-Open or create a new one if needed. Thank you.
