### ISSUE TITLE
Links to guidelines in validator don't work properly

### ISSUE THREAD

**Issue by cgutteridge** [openaire/guidelines#25]
I've been trying to use the validator to review our endpoint and the https://guidelines.openaire.eu/wiki/Literature_Guidelines:_Metadata_Field_Access_Level "view guideline" links just redirect to the top of the documentation. The titles in the documentation don't quite match up so it's adding extra work to understand it all.

**Comment by joschirr** [comment]
Thank you for notification. The links to the fields / properties are updated in the validator service now.
