### ISSUE TITLE
Research Data guideline - Contributors and validation

### ISSUE THREAD

**Issue by yurj** [openaire/guidelines#28]
Hi!

 why this example throws error in openaire validator?

<contributors>
<contributor contributorType="Funder" >
<contributorName>European Commission</contributorName>
<nameIdentifier nameIdentifierScheme="info" >info:eu-repo/grantAgreement/EC/H2020/123456/</nameIdentifier>
</contributor>
</contributors> 

This should be valid DataciteXML v3.1. Also, can some more complete example be shown? The last update in this guide is 5 years ago...

**Comment by ACz-UniBi** [comment]
Dear @yurj ,

could you retry and give us feedback about it.
In the context of Data Archive Guidelines, please open a new issue at https://github.com/openaire/guidelines-data-archives/issues
